#!/usr/bin/env python3
"""Bake the module's anti-aliased fonts into a C header.

The TRACE module has no font engine and no files, so every face it uses is
rendered here once, as 8-bit coverage maps, at 1x and 2x: the module renders at
640x480 or 1280x960 depending on how big the picture is on screen, and picks
the matching set so text is always drawn at its real pixel size (TERMinator
scales with nearest-neighbour, which would smear a scaled-up glyph).

The face is Ubuntu (Ubuntu Font Licence 1.0, which allows embedding and
redistribution). Character 127 in every font is the degree sign.

Usage: make_fonts.py [out.h] [Ubuntu.ttf]
"""
import sys

from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/truetype/ubuntu/Ubuntu[wdth,wght].ttf"

ASCII = "".join(chr(c) for c in range(32, 127)) + "°"
DIGITS = " -0123456789°"

# name, weight, logical pixel size, characters
FACES = [
    ("SMALL", b"Medium",  10, ASCII),     # small caps labels
    ("BODY",  b"Regular", 12, ASCII),
    ("BOLD",  b"Bold",    12, ASCII),
    ("HEAD",  b"Medium",  16, ASCII),
    ("TITLE", b"Medium",  21, ASCII),     # the condition in the hero
    ("HUGE",  b"Light",   78, DIGITS),    # the temperature
]
SCALES = (1, 2)


def code_of(ch):
    return 127 if ch == "°" else ord(ch)


def bake(ttf, weight, px, chars):
    font = ImageFont.truetype(ttf, px)
    font.set_variation_by_name(weight)
    ascent, descent = font.getmetrics()
    line = ascent + descent
    pad = px
    glyphs = {}
    for ch in chars:
        adv = int(round(font.getlength(ch)))
        img = Image.new("L", (adv + pad * 2, line + pad * 2), 0)
        ImageDraw.Draw(img).text((pad, pad + ascent), ch, font=font, fill=255, anchor="ls")
        box = img.getbbox()
        if box is None:
            glyphs[code_of(ch)] = (0, 0, 0, 0, adv, b"")
            continue
        x0, y0, x1, y1 = box
        crop = img.crop(box)
        glyphs[code_of(ch)] = (x0 - pad, y0 - pad, x1 - x0, y1 - y0, adv, crop.tobytes())
    return ascent, line, glyphs


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "fonts.h"
    ttf = sys.argv[2] if len(sys.argv) > 2 else TTF

    lines = [
        "// Generated by tools/make_fonts.py -- do not edit.",
        "// Ubuntu (Ubuntu Font Licence 1.0), baked to 8-bit coverage at 1x and 2x.",
        "// Character 127 is the degree sign.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "typedef struct { int16_t x, y; uint8_t w, h, adv, pad; uint32_t off; } FontGlyph;",
        "typedef struct { uint8_t ascent, line, first, count; const FontGlyph *g; const uint8_t *alpha; } FontFace;",
        "",
    ]
    faces = []
    total = 0
    for name, weight, size, chars in FACES:
        for s in SCALES:
            ascent, line, glyphs = bake(ttf, weight, size * s, chars)
            first = min(glyphs)
            last = max(glyphs)
            tag = f"{name.lower()}{s}"
            blob = bytearray()
            table = []
            for code in range(first, last + 1):
                if code in glyphs:
                    x, y, w, h, adv, data = glyphs[code]
                    table.append((x, y, w, h, adv, len(blob)))
                    blob += data
                else:
                    table.append((0, 0, 0, 0, 0, 0))
            total += len(blob)
            lines.append(f"static const uint8_t g_{tag}_alpha[{max(len(blob), 1)}] = {{")
            for i in range(0, len(blob), 32):
                lines.append("    " + ",".join(str(b) for b in blob[i:i + 32]) + ",")
            if not blob:
                lines.append("    0,")
            lines.append("};")
            lines.append(f"static const FontGlyph g_{tag}_glyphs[{len(table)}] = {{")
            for t in table:
                lines.append("    {%d,%d,%d,%d,%d,0,%d}," % t)
            lines.append("};")
            faces.append((name, s, ascent, line, first, len(table), tag))

    lines.append("")
    lines.append("enum { " + ", ".join(f"F_{n}" for n, *_ in FACES) + ", F_COUNT };")
    lines.append(f"static const FontFace g_fonts[{len(SCALES)}][F_COUNT] = {{")
    for s in SCALES:
        lines.append("    {")
        for name, fs, ascent, line, first, count, tag in faces:
            if fs == s:
                lines.append(f"        {{{ascent},{line},{first},{count},g_{tag}_glyphs,g_{tag}_alpha}},  // {name}")
        lines.append("    },")
    lines.append("};")
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"{out}: {total} bytes of glyph coverage")


if __name__ == "__main__":
    main()
